disabled_rules:
  - colon
  - comma
  - control_statement
  - identifier_name
  - type_name
  - trailing_comma

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Pods
  - vendor/bundle

force_cast: error

force_try:
  severity: error

type_body_length:
  - 300
  - 400

function_body_length:
  - 200
  - 300

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 4
